### ISSUE TITLE
Modernize Perl Macros

### ISSUE THREAD

**Issue by joebonrichie** [getsolus/ypkg#65]
We currently prefer `Build.PL` however `Module::Build` isn't well maintained so we should consider defaulting back to `Makefile.PL` as `ExtUtils::MakeMaker` is part of the standard perl package.

https://fedoraproject.org/wiki/Perl/Tips#Makefile.PL_vs_Build.PL

**Comment by ermo** [comment]
Unless Tracey overrules this, I think we should follow fedora's advice and go with `ExtUtils::MakeMaker` based macros.

They look fine in Serpent, so we already merged them there.

**Comment by TraceyC77** [comment]
The discussion that Fedora page links to is from 2013, and the information on that page is out of date. Module::Build was last updated [2023-04-28](https://metacpan.org/dist/Module-Build). Module::Build can't be the "new kid on the block" if it's been around since before 2013. (The new kids on the block these days are things like [dzil](https://dzil.org/index.html)).
I did confirm that [Module::Build was removed from perl core as of 5.22.0](https://perldoc.perl.org/perl5220delta#Removed-Modules-and-Pragmata) (the current perl version is 5.38.2).

With that said, I agree that we should default to Makefile.PL and fall back to Build.PL if it exists. Additional current data below (might be useful if we make a docs page for this).

Most of the modules I have experience with use ExtUtils::MakeMaker, it's a well used standard and a more mature project. It's more actively developed than Module::Build. You can see this if you look at their module pages, particularly activity, testers and bus factor count:
[ExtUtils::MakeMaker](https://metacpan.org/dist/ExtUtils-MakeMaker) - last modified [2023-03-26](https://metacpan.org/release/BINGOS/ExtUtils-MakeMaker-7.70/source)
[Module::Build](https://metacpan.org/pod/Module::Build) - last modified [2023-04-29](https://metacpan.org/release/LEONT/Module-Build-0.4234/source)

The official perl docs on [making modules](https://perldoc.perl.org/perlnewmod) result in a `Makefile.PL`.
Additionally, newer module packaging utilities like [dzil](https://dzil.org/index.html) produce a `Makefile.PL`.

**Comment by TraceyC77** [comment]
Note: Changes would be in https://github.com/getsolus/ypkg/blob/master/ypkg2/rc.yml
